grafana:
  datasource:
    uid: KLUVORSnk
    type: prometheus
  namespace:
    - b2c-dev
    - dev
    - dev-data
    - setelpay-dev
    - ucommp-dev
    - ufp-dev
    - ulp-dev
    - pre-prod
    - setelpay-pre-prod
    - ucommp-pre-prod
    - ufp-pre-prod
    - ulp-pre-prod
    - setelpay-staging
    - ucommp-staging
    - ufp-staging
    - ulp-staging
    - staging
  environment:
    - dev
    - pre-prod
    - prod
